In [18]:
import numpy as np
import pandas as pd

In [19]:
dataset = pd.read_csv("new_data.csv")

In [20]:
dataset.head()

director_name     actor_1_name      actor_2_name          actor_3_name  \
0      James Cameron      CCH Pounder  Joel David Moore             Wes Studi   
1     Gore Verbinski      Johnny Depp     Orlando Bloom        Jack Davenport   
2         Sam Mendes  Christoph Waltz      Rory Kinnear      Stephanie Sigman   
3  Christopher Nolan        Tom Hardy    Christian Bale  Joseph Gordon-Levitt   
4        Doug Walker      Doug Walker        Rob Walker               unknown   

                            genres  \
0  Action|Adventure|Fantasy|Sci-Fi   
1         Action|Adventure|Fantasy   
2        Action|Adventure|Thriller   
3                  Action|Thriller   
4                      Documentary   

                                         movie_title  \
0                                             avatar   
1           pirates of the caribbean: at world's end   
2                                            spectre   
3                              the dark knight rises   
4  star wars: episode vii - the force awakens    ...   

                                    combined_feature  
0  CCH Pounder Joel David Moore Wes Studi James C...  
1  Johnny Depp Orlando Bloom Jack Davenport Gore ...  
2  Christoph Waltz Rory Kinnear Stephanie Sigman ...  
3  Tom Hardy Christian Bale Joseph Gordon-Levitt ...  
4  Doug Walker Rob Walker unknown Doug Walker Doc...

In [21]:
dataset.columns

Index(['director_name', 'actor_1_name', 'actor_2_name', 'actor_3_name',
       'genres', 'movie_title', 'combined_feature'],
      dtype='object')

In [22]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5364 entries, 0 to 5363
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   director_name     5364 non-null   object
 1   actor_1_name      5364 non-null   object
 2   actor_2_name      5364 non-null   object
 3   actor_3_name      5364 non-null   object
 4   genres            5364 non-null   object
 5   movie_title       5364 non-null   object
 6   combined_feature  5364 non-null   object
dtypes: object(7)
memory usage: 293.5+ KB


In [23]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
count_matrix = vectorizer.fit_transform(dataset["combined_feature"])

In [24]:
print(vectorizer.get_feature_names())

['300ml', '50', 'aagesen', 'aaliyah', 'aarniokoski', 'aaron', 'aasheekaa', 'aasif', 'abad', 'abadie', 'abai', 'abascal', 'abbas', 'abbass', 'abbess', 'abbie', 'abbott', 'abby', 'abdalla', 'abdul', 'abdulayev', 'abe', 'abel', 'abelanski', 'abell', 'abhishek', 'abigail', 'abita', 'abittan', 'abkarian', 'able', 'abo', 'aboulafia', 'abraham', 'abrahams', 'abrahamson', 'abrams', 'abromeit', 'abtahi', 'acar', 'ace', 'acevedo', 'achabbakhe', 'acker', 'ackerman', 'ackland', 'ackles', 'acres', 'action', 'adah', 'adam', 'adamczyk', 'adams', 'adamson', 'addison', 'adduci', 'addy', 'adel', 'adelaide', 'adelman', 'adelstein', 'aden', 'adetuyi', 'adhir', 'adina', 'aditya', 'adjani', 'adkins', 'adler', 'adloff', 'adolfo', 'adolphe', 'adorée', 'adoti', 'adrian', 'adriana', 'adriane', 'adrianne', 'adriano', 'adrien', 'adrienne', 'adsit', 'adventure', 'adèle', 'ae', 'aeona', 'afable', 'affleck', 'agalakova', 'agame', 'agapova', 'agata', 'agee', 'aglaya', 'agnefjall', 'agnes', 'agnia', 'agnieszka', 'agni

In [25]:
print(count_matrix.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [26]:
from sklearn.metrics.pairwise import cosine_similarity
simlarity_score = cosine_similarity(count_matrix)
print(simlarity_score)

[[1.         0.24174689 0.16116459 ... 0.         0.07412493 0.        ]
 [0.24174689 1.         0.18181818 ... 0.         0.0836242  0.        ]
 [0.16116459 0.18181818 1.         ... 0.         0.0836242  0.09090909]
 ...
 [0.         0.         0.         ... 1.         0.0877058  0.        ]
 [0.07412493 0.0836242  0.0836242  ... 0.0877058  1.         0.0836242 ]
 [0.         0.         0.09090909 ... 0.         0.0836242  1.        ]]


In [27]:
movie_user_likes = "Avatar"

In [28]:
# Get Index of the movie from the dataset
def get_movie_index(movie_user_likes):
    for i in range(len(dataset['movie_title'])):
        if dataset['movie_title'][i] == movie_user_likes.lower():
            return i

In [29]:
movie_index = get_movie_index(movie_user_likes)

In [30]:
s_score = list(enumerate(simlarity_score[movie_index]))

In [31]:
s_score

[(0, 0.9999999999999999),
 (1, 0.24174688920761409),
 (2, 0.16116459280507606),
 (3, 0.08058229640253803),
 (4, 0.0),
 (5, 0.3086066999241839),
 (6, 0.14285714285714288),
 (7, 0.2964997266644405),
 (8, 0.2314550249431379),
 (9, 0.3086066999241839),
 (10, 0.3086066999241839),
 (11, 0.16903085094570333),
 (12, 0.24174688920761409),
 (13, 0.16116459280507606),
 (14, 0.37062465833055064),
 (15, 0.2314550249431379),
 (16, 0.24174688920761409),
 (17, 0.3450327796711771),
 (18, 0.253546276418555),
 (19, 0.24174688920761409),
 (20, 0.14285714285714288),
 (21, 0.253546276418555),
 (22, 0.15430334996209194),
 (23, 0.16903085094570333),
 (24, 0.2964997266644405),
 (25, 0.2964997266644405),
 (26, 0.28571428571428575),
 (27, 0.3223291856101521),
 (28, 0.2964997266644405),
 (29, 0.3571428571428572),
 (30, 0.14824986333222026),
 (31, 0.3086066999241839),
 (32, 0.3086066999241839),
 (33, 0.38575837490522985),
 (34, 0.07412493166611013),
 (35, 0.3086066999241839),
 (36, 0.14824986333222026),
 (37, 0.32

In [32]:
s_score_sorted = sorted(s_score, key = lambda x: x[1], reverse = True)

In [33]:
s_score_sorted

[(0, 0.9999999999999999),
 (2384, 0.4629100498862758),
 (595, 0.44474958999666075),
 (1073, 0.44474958999666075),
 (1626, 0.41403933560541256),
 (260, 0.4029114820126901),
 (3448, 0.4029114820126901),
 (632, 0.40089186286863654),
 (3203, 0.40089186286863654),
 (33, 0.38575837490522985),
 (52, 0.38575837490522985),
 (84, 0.38575837490522985),
 (1059, 0.38575837490522985),
 (1624, 0.38575837490522985),
 (2020, 0.38575837490522985),
 (2396, 0.38575837490522985),
 (4684, 0.38575837490522985),
 (14, 0.37062465833055064),
 (209, 0.37062465833055064),
 (214, 0.37062465833055064),
 (215, 0.37062465833055064),
 (217, 0.37062465833055064),
 (218, 0.37062465833055064),
 (311, 0.37062465833055064),
 (414, 0.37062465833055064),
 (478, 0.37062465833055064),
 (1062, 0.37062465833055064),
 (1464, 0.37062465833055064),
 (1960, 0.37062465833055064),
 (2175, 0.37062465833055064),
 (2574, 0.37062465833055064),
 (2903, 0.37062465833055064),
 (3209, 0.37062465833055064),
 (3506, 0.37062465833055064),
 (4464

In [34]:
# Top 10 similar movies
indexes = [t[0] for t in s_score_sorted[0:10]]

In [35]:
indexes

[0, 2384, 595, 1073, 1626, 260, 3448, 632, 3203, 33]

In [36]:
# Get Movie Title from Index
def get_movie_names(indexes):
    movie_match = []
    for index in indexes:
        movie_match.append(dataset['title'][index].title())
    return movie_match

In [37]:
top_10_movie_match = get_movie_names(indexes)

KeyError: 'title'